### ISSUE TITLE
Mark F-Droid apps

### ISSUE THREAD

**Issue by TheLastProject** [techlore/Plexus-app#1]
**Describe the bug**
Apps installed from F-Droid are shown, despite these often being Google-independent versions in the first place.

**To Reproduce**
1. Start app
2. See several F-Droid apps listed

**Expected behavior**
As per Plexus design, F-Droid versions of apps are expected to work fine (is this a good assumption? I'm not sure, Home Assistant had no notifications in its F-Droid build for ages). So having them all listed with X/X (as reviewing F-Droid apps wasn't allowed last time I checked) makes the installed app list pretty unreadable.

**Additional context**
I am not sure what the best way to deal with this is (special coloured checkmark?) but there is a fairly (but not 100%) reliable way to detect F-Droid versions of apps as very little apps opt into reproducible builds: read the signature.

All F-Droid app signatures seem to look as follows:

Signer Certificate
Subject: CN=FDroid,OU=FDroid,O=fdroid.org,L=ORG,ST=ORG,C=UK
Issuer: CN=FDroid,OU=FDroid,O=fdroid.org,L=ORG,ST=ORG,C=UK

P.S.: Would it make sense to in the review JSON have some F-Droid field to mark any issues with using the F-Droid version of an app if it exists (no notifications) or should this just be a note in DeGoogled or microG?

**Comment by henryistaken** [comment]
Hey, thanks for sharing this!

- The JSON format is actually temporary for the purposes of developing the application. We're currently working on an API that will be replacing it.
- This is all part of our final goal of allowing submissions directly in the app, a workflow that will not play nicely with the current GitHub workflow.

The real reason F-Droid was never originally allowed was as you said, most(!) apps are expected to work, and since the submissions process was 100% manual, we wanted to make it easier for people to contribute. (and easier for us to manage) But once the above points are completed, we will not be discriminating submissions since it'll be more-or-less automated.

We're playing around with different methods of outlining the source of applications (Google Play, F-Droid, etc.) in a way that makes sense to people. So there will be duplicate datapoints to help people see any differences across versions of applications. (Ex. Telegram from f-droid vs google play, or Signal from its website vs the Google Play version) Still haven't finalized the details, but we'll do our best to bring this together cleanly.

**Comment by 12people** [comment]
Not sure if this belongs in this issue, but it's worth noting that some people who only install through Google Play use Plexus to see if they could migrate away.

For those people, it'd be useful if Plexus could communicate that an app they installed from Google Play is also available via F-Droid.

**Comment by StellarSand** [comment]
Both issues have been solved in the latest version.
