### ISSUE TITLE
What to do with newer app versions breaking things?

### ISSUE THREAD

**Issue by TheLastProject** [techlore/Plexus-app#3]
Take for example PayPal. Right now it's rated 4 for de-Googled and 3 for microG on version 0.0.0.

However, version 8.16.0 crashes on startup on microG: https://github.com/microg/GmsCore/issues/1710

Do I:
1. Add a new entry for PayPal with the new version number with microG rating 1 and de-Googled rating X
2. Update the current PayPal entry with the new version number and set microG to 1 (and leave de-Googled as it is? Or force it back to X as that version is not tested de-Googled yet?)

Option 1 seems more sane to me, as some apps release updates quite often and workflow 2 would most likely cause either microG or de-Googled for popular apps to either be X all the time or give a misleading view as the test was for an older version.

**Comment by the-weird-aquarian** [comment]
Currently all app versions are set to 0.0.0.0 since it's taken from the already existing [plexus.csv](https://github.com/techlore/plexus/blob/master/src/data/Plexus.csv) data and we don't know what version the app was tested on. So for now update the current entry and update de-Googled as X. 

Support for multiple app versions coming soon.

**Comment by StellarSand** [comment]
You can use the latest version which resolved this.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/techlore/Plexus-app/issues/3#issuecomment-2194786552

@StellarSand, as in, it now supports multiple application versions?

**Comment by StellarSand** [comment]
Yes it does, but I guess after 6 hours you already know this by using the app. :smile:
