### ISSUE TITLE
Two apps cannot be submitted.

### ISSUE THREAD

**Issue by marcdw1289** [techlore/Plexus-app#33]
### Description
I have two apps on multiple ROMs that cannot be submitted.

Foldersync Pro ( dk.tacit.android.foldersync.full ),  via Aurora Store.
MiXplorer Silver (com.mixplorer.silver) via Aurora Store.

The direct downloaded FolderSync Pro ( dk.tacit.android.foldersync.app )

### Steps to reproduce the behaviour
1. Try to submit either app
2. See error

### Screenshots/error messages (optional)
Error while submitting data: 422.

**Comment by StellarSand** [comment]
I need one information from you. When MiXplorer Silver is installed on your device, does it show up as only "MiXplorer" ?

**Comment by marcdw1289** [comment]
> I need one info from you. When MiXplorer Silver is installed on your device, does it show up as only "MiXplorer" ?
Ah yes. It does indeed only show up as MiXplorer. In Settings and in various launchers.

Silver is just MiXplorer with additional addons. Though it is a paid app there is no license checking nor InApp Purchase checks. Its status is Gold on both microG and bareAOSP.

Ah, I went to my other phone just now and was able to make a submission.
Wow, that was superfast.

**Comment by StellarSand** [comment]
Yeah so currently the API checks for both `Name` & `Package name` before adding a new app to the database. One MiXplorer already exists (although with a different package name) in the database and since MiXplorer Silver also shows up as "MiXplorer", it gives `422` error which means app already exists.
The API dev won't be available for a few weeks, but once he is available, I'll ask him to drop the name check requirement and only check for package names.

So I've added MiXplorer Silver from  my end with the exact name instead of just MiXplorer. Now you'll see two different apps: `MiXplorer` & `MiXplorer Silver`, allowing you to submit ratings for both.

Other similar cases include `1Password` which I had to rename as `1Password (old)` & `1Password (new)`.
`FileSync Pro` also faces the same issue.
