### ISSUE TITLE
Sandboxed Google Play

### ISSUE THREAD

**Issue by mercertom** [techlore/Plexus-app#7]
The main use of Plexus is deciding between GrapheneOS and the rest. 

I was unable to run one app on GrapheneOS that Plexus said I could, and I'm delightfully able to run a banking app and Lime on GrapheneOS that Plexus made me think I wouldn't have been able to.

When I went to contribute and fix this, the contributing guidelines made it clear that the left side is for no google play at all, and right side is for microG. I'm pretty sure that everyone already knows that almost nothing works with no google framework/services at all.

Isn't the point of this app deciding between GrapheneOS and the rest? Seeing which apps you'll be able to run with regular ROMs (all), the microGs like Lineage or Calyx and many more (the right hand side), and then the strictest (GrapheneOS)?

I don't really want to make a third column of data. I'm pretty sure the current left side is useless to most users of the app, who also see it as shorthand for "Graphene" (until/unless they read the contributing guidelines).

**Comment by the-weird-aquarian** [comment]
Hey Tom.

- The main use of Plexus is not deciding between GrapheneOS and rest but beween degoogled roms and microG, be it Lineage, GrapheneOS, Calyx or anything else.

- > I was unable to run one app on GrapheneOS that Plexus said I could, and I'm delightfully able to run a banking app and Lime on GrapheneOS that Plexus made me think I wouldn't have been able to.

     While this could be a sandboxed google play thing but this also could be because the current data is the same as in [this CSV](https://github.com/techlore/plexus/blob/master/src/data/Plexus.csv) & might not be exactly up to date. There are apps in which one of the version works perfectly and some other version doesn't or vice versa. This is all being worked on so please be patient.

- > almost nothing works with no google framework/services at all.

     This is only partially true. In the app if you sort based on "Perfect" degoogled rating, you'll find many apps that do work without any issue. 

- During the development of this app, Henry did mention he wanted to add sandboxed google play rating and notes but after some discussions we decided against it, mainly because:

  1.  We assumed that it is not much different than normal google services because at the end of the day it's just play services which is isolated so apps should work normally but neither one of us had the time or resources to test out each and every app ourselves to verify these claims.
  2. The left side is for degoogled rating and on the right there's microG rating and adding another rating would mean design changes not only in the app but also on the website side of things. 
  3. It would add a third data point (like you mentioned) and we wanted to prioritize the current task at hand, which was getting this app ready and working with whatever data was available.

**Comment by mercertom** [comment]
> The main use of Plexus is not deciding between GrapheneOS and rest but beween degoogled roms and microG, be it Lineage, GrapheneOS, Calyx or anything else.

I don't understand this. How could anyone be wondering whether an app will work with no google whatsoever?

GrapheneOS is sandboxed G, not microG.

Essentially nobody is wondering whether no google will let them use google apps. This use case is not valuable. Replace it with GrapheneOS (sandboxed G).

>While this could be a sandboxed google play thing but this also could be because the current data is the same as in [this CSV](https://github.com/techlore/plexus/blob/master/src/data/Plexus.csv) & might not be exactly up to date.

Nope. It's a sandboxed g thing. The csv is the same as what I see in the app. X X for both Lime and the banking app, but both work great. OF COURSE both won't work with no google (the use case with no value). I wouldn't wonder this, because it's obvious. But I was actually curious whether either would work with microG or sandboxed G.

I stated (ii). But I also went further and stated that you should _replace_ degoogled (useless) with sandboxed (useful).

(iii) No, it wouldn't. It would _replace_ all the useless data points for no google whatsoever.

**Comment by the-weird-aquarian** [comment]
> How could anyone be wondering whether an app will work with no google whatsoever?
Essentially nobody is wondering whether no google will let them use google apps

Plexus is not limited to google apps. Just because google apps don't work doesn't mean other apps won't.
Like I said earlier. in the app if you sort based on "Perfect" degoogled rating, you'll find many apps that do work without any issue. And there are probably others too which are not in this data.

> The csv is the same as what I see in the app

Of course you do because it is. The CSV is not up to date. Check last updated date. Most of them are 2020 and 2021. only 50 apps have last updated as 2022 and even they aren't up to date with latest versions.

> X X for both Lime and the banking app, but both work great.

X stands for "Not Tested" and **not** "Not working". Check [what do the ratings mean](https://github.com/techlore/Plexus-app#what-do-the-ratings-mean) or go to "Help" within the app for more info. 
This further supports what I said earlier about assuming sandboxed google play being just normal play services but isolated so apps would work but couldn't test each app to verify this claim, which was one of the reasons we decided not to include this.

> Main reason people don't use graphene is that sandboxed G doesn't work for many banking apps people find vital and gpay.

That's due to SafetyNet. Any normal custom rom which does not pass SafetyNet by default wouldn't also have banking apps working. There's a Magisk module to help you pass SafetyNet. Check [official statement in GrapheneOS website about banking apps](https://grapheneos.org/usage#banking-apps).

**Comment by mercertom** [comment]
> Plexus is not limited to google apps. Just because google apps don't work doesn't mean other apps won't.

I said nothing about "google apps". Please stay on-topic. What I repeatedly referred to was whether an app (not a google app) will work with no google whatsoever.

>Like I said earlier. in the app if you sort based on "Perfect" degoogled rating, you'll find many apps that do work without any issue. 

Surer are. My point is and always has been that whether an app has a perfect degoogled rating or an anti-perfect degoogled rating, it's (almost) never a surprise. So why show the degoogled rating? My suggestion: don't. Replace degoogled ratings (nobody cares) with GrapheneOS sandboxed g ratings (lots of people care).

>Of course you do because it is. The CSV is not up to date. 

Then wtf did you link to the CSV? Your words implied the CSV was more recent than the app, and that the reason the app was out-of-date was that it hadn't been updated like the CSV had. Seriously, what the hell? Why link to ANOTHER out-of-date source? What's the point?

>That's due to SafetyNet.

I'm aware. My statement is still relevant and correct.

> Main reason people don't use graphene is that sandboxed G doesn't work for many banking apps people find vital and gpay.

I didn't ask, nor does this statement depend upon, _why_ this is the case.

**Comment by henryistaken** [comment]
> The main use of Plexus is deciding between GrapheneOS and the rest.

It isn't. The use is to provide data regarding compatibility on *all* ROMs w/ MicroG or No Play Services. This is very clearly outlined. Not everything is a ROM war.

> I was unable to run one app on GrapheneOS that Plexus said I could, and I'm delightfully able to run a banking app and Lime on GrapheneOS that Plexus made me think I wouldn't have been able to. When I went to contribute and fix this, the contributing guidelines made it clear that the left side is for no google play at all, and right side is for microG.

Almost *all* apps should work on gOS via Sandboxed Play Services, so we didn't see the need in collecting data for it. With that said, if we see more demand for this, then we'll look into incorporating it.

> I'm pretty sure that everyone already knows that almost nothing works with no google framework/services at all.

This isn't true, and outlines the core reason this project exists. Many apps actually do work on a completely de-googled device. We look to provide that information. If something doesn't match your experience, then please contribute to the project so other users are updated.

This doesn't seem to be heading anywhere, so I'm going to close the issue. With that said, we'll be sure to keep this conversation in mind if more people think it's useful to collect data on sandboxed play services, but based on everything we're hearing - the compatibility is excellent with the exception of some banking apps (Which is directly mentioned on their site as referenced by @the-weird-aquarian and shouldn't come as a surprise to people)
